---
name: Build and publish golang image

on:
  workflow_dispatch: {}
  # Run every day at 5AM UTC
  schedule:
    - cron: '0 5 * * *'

env:
  QUAY_ORG: projectquay
  QUAY_REPO: golang
  QUAY_USER: projectquay+claircore_github

jobs:
  golang-image:
    name: Build and publish golang image
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        go: ['1.17', '1.18']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check verisons and dates
        run: |
          v=$(.github/scripts/get-latest-golang-minor-version.sh ${{ matrix.go }})
          t=$(curl -sSLf "https://quay.io/api/v1/repository/${QUAY_ORG}/${QUAY_REPO}/tag/?specificTag=${{ matrix.go }}&onlyActiveTags=true" |
            jq -r '.tags[0].last_modified//"Thu, 01 Jan 1970 00:00:00 -0000"')
          g=$(curl -sSLfI --http2 "https://dl.google.com/go/go${v}.linux-amd64.tar.gz" |
            awk 'BEGIN {FS=": "}/^last-modified/{print $2}')
          cat <<.
          ::notice title=Latest Go version::$v
          ::notice title=Latest tag update::$t
          ::notice title=Go version update::$g
          .
          cat <<. >>"$GITHUB_ENV"
          GO_VERSION=$v
          TAG_LAST_MODIFIED=$t
          GO_LAST_MODIFIED=$g
          .
      - name: Decide whether we need to build new golang image
        run: |
          TAG=$(date -d "${TAG_LAST_MODIFIED}" +%s)
          GO=$(date -d "${GO_LAST_MODIFIED}" +%s)
          if test "$GO" -gt "$TAG"; then
            echo "BUILD_IMAGE=1" >> "$GITHUB_ENV"
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
        if: env.BUILD_IMAGE == 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: env.BUILD_IMAGE == 1
      - uses: docker/login-action@v2
        if: env.BUILD_IMAGE == 1
        with:
          registry: quay.io
          username: ${{ env.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Build and Publish golang image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
          context: etc
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            quay.io/${{ env.QUAY_ORG }}/${{ env.QUAY_REPO }}:${{ matrix.go }}
        if: env.BUILD_IMAGE == 1
